import type { Diagram } from '../../../src/lib/diagram';

// Logical diagrams; official sources and verification dates live on each product's MDX page.
export const diagrams = {
  workers: {
    title: 'Inside a Worker request',
    summary:
      'An HTTP handler connects application code to resources through bindings, then returns a response.',
    width: 900,
    height: 485,
    nodes: [
      {
        id: 'request',
        label: 'HTTP request',
        subtitle: 'Request object',
        icon: 'browser',
        detail:
          'An incoming HTTP request is passed to the Worker’s fetch handler as a Request object.',
        x: 140,
        y: 55,
        href: '#piece-request',
      },
      {
        id: 'handler',
        label: 'fetch handler',
        subtitle: 'Your application code',
        icon: 'compute',
        detail:
          'The fetch handler runs your application logic and returns a Response. Workers use the workerd runtime.',
        x: 450,
        y: 55,
        href: '#piece-handler',
      },
      {
        id: 'bindings',
        label: 'env bindings',
        subtitle: 'Configured resources',
        icon: 'workflow',
        detail:
          'Bindings expose configured resources to code through env. The binding is the interface; the resource it points to can be local or remote during development.',
        x: 760,
        y: 55,
        href: '#piece-bindings',
      },
      {
        id: 'response',
        label: 'HTTP response',
        subtitle: 'Returned to the caller',
        icon: 'message',
        detail:
          'Return a Response from the handler to send status, headers, and a body back to the caller.',
        x: 140,
        y: 340,
        href: '#piece-response',
      },
      {
        id: 'data',
        label: 'Data services',
        subtitle: 'KV · R2 · D1',
        icon: 'database',
        detail:
          'Your code can call configured KV, R2, and D1 bindings. Choose the storage model that matches the data; these services are alternatives, not mandatory stages.',
        x: 450,
        y: 340,
        href: '#piece-data',
      },
      {
        id: 'background',
        label: 'Background work',
        subtitle: 'Queues · Workflows',
        icon: 'queue',
        detail:
          'Queue and Workflow bindings let your Worker send messages or create durable executions. Each service has separate usage accounting.',
        x: 760,
        y: 340,
        href: '#piece-background',
      },
    ],
    edges: [
      {
        from: 'request',
        to: 'handler',
        d: 'M166 87 L423 87',
        label: 'HTTP',
        x: 295,
        y: 72,
      },
      {
        from: 'handler',
        to: 'bindings',
        d: 'M475 87 L740 87',
        label: 'env',
        x: 605,
        y: 72,
      },
      {
        from: 'bindings',
        to: 'data',
        d: 'M742 87 L664 87 Q652 87 652 99 L652 223 Q652 235 640 235 L462 235 Q450 235 450 247 L450 343',
        label: 'read / write',
        x: 592,
        y: 223,
      },
      {
        from: 'bindings',
        to: 'background',
        d: 'M778 87 L856 87 Q868 87 868 99 L868 293 Q868 305 856 305 L772 305 Q760 305 760 317 L760 352',
        label: 'send / create',
        x: 814,
        y: 229.5,
        kind: 'message',
      },
      {
        from: 'handler',
        to: 'response',
        d: 'M425 96 L354 96 Q342 96 342 108 L342 273 Q342 285 330 285 L152 285 Q140 285 140 297 L140 351',
        label: 'return',
        x: 265,
        y: 273,
      },
    ],
  },
  pages: {
    title: 'From repository to a Pages request',
    summary:
      'A Git-integrated example: build assets, deploy the site, then serve static content or run a Function.',
    width: 900,
    height: 485,
    nodes: [
      {
        id: 'repository',
        label: 'Git repository',
        subtitle: 'GitHub / GitLab',
        icon: 'code',
        detail:
          'A connected GitHub or GitLab repository can trigger Pages builds when you push changes. This diagram shows the Git integration path.',
        x: 140,
        y: 55,
        href: '#piece-repository',
      },
      {
        id: 'build',
        label: 'Build',
        subtitle: 'Command → output',
        icon: 'compute',
        detail:
          'Pages runs the configured build command and publishes the configured output directory. Build concurrency and monthly allowances depend on the Pages plan.',
        x: 450,
        y: 55,
        href: '#piece-build',
      },
      {
        id: 'assets',
        label: 'Static assets',
        subtitle: 'Deployed site files',
        icon: 'browser',
        detail:
          'The build output becomes the deployed site’s static content. Individual file-size and file-count limits apply.',
        x: 760,
        y: 55,
        href: '#piece-assets',
      },
      {
        id: 'visitor',
        label: 'Browser request',
        subtitle: 'Your site URL',
        icon: 'browser',
        detail:
          'Visitors request the deployed site. Static content and dynamic Functions are distinct parts of a Pages application.',
        x: 140,
        y: 340,
        href: '#piece-visitor',
      },
      {
        id: 'functions',
        label: 'Pages Functions',
        subtitle: 'onRequest(context)',
        icon: 'compute',
        detail:
          'Pages routes /functions files to onRequest(context) handlers. These run on the Workers runtime and use Workers quotas. Advanced mode instead uses a _worker.js module with a fetch handler.',
        x: 450,
        y: 340,
        href: '#piece-functions',
      },
      {
        id: 'bindings',
        label: 'Resource bindings',
        subtitle: 'Data used by Functions',
        icon: 'database',
        detail:
          'Pages Functions can use configured bindings to resources such as KV, R2, and D1. Check Pages-specific support and local-development restrictions.',
        x: 760,
        y: 340,
        href: '#piece-bindings',
      },
    ],
    edges: [
      {
        from: 'repository',
        to: 'build',
        d: 'M167 87 L423 87',
        label: 'push',
        x: 295,
        y: 72,
      },
      {
        from: 'build',
        to: 'assets',
        d: 'M475 87 L732 87',
        label: 'publish',
        x: 605,
        y: 72,
      },
      {
        from: 'visitor',
        to: 'assets',
        d: 'M166 381 L236 381 Q248 381 248 369 L248 234 Q248 222 260 222 L640 222 Q652 222 652 210 L652 99 Q652 87 664 87 L732 87',
        label: 'static route',
        x: 600,
        y: 210,
      },
      {
        from: 'visitor',
        to: 'functions',
        d: 'M166 372 L423 372',
        label: 'dynamic route',
        x: 295,
        y: 357,
      },
      {
        from: 'functions',
        to: 'bindings',
        d: 'M475 372 L735 372',
        label: 'binding',
        x: 605,
        y: 357,
      },
    ],
  },
  kv: {
    title: 'A KV read is a cache lookup',
    summary:
      'Reads use a cache hierarchy; writes go to central stores. This is why local success does not establish global freshness.',
    width: 900,
    height: 485,
    nodes: [
      {
        id: 'reader',
        label: 'Worker reader',
        subtitle: 'get(key)',
        icon: 'compute',
        detail:
          'A Worker reads through its KV namespace binding. A cached read can avoid going back to the central stores.',
        x: 140,
        y: 55,
        href: '#piece-reader',
      },
      {
        id: 'edge',
        label: 'Location cache',
        subtitle: 'Hot read',
        icon: 'keys',
        detail:
          'Frequently read values can be served from the cache at a Cloudflare location. A cached value may lag a recent write.',
        x: 450,
        y: 55,
        href: '#piece-edge',
      },
      {
        id: 'regional',
        label: 'Upper cache tiers',
        subtitle: 'Cache miss path',
        icon: 'keys',
        detail:
          'On a cache miss, KV checks higher cache tiers before falling back to the central stores. This diagram simplifies the regional and central cache tiers.',
        x: 760,
        y: 55,
        href: '#piece-regional',
      },
      {
        id: 'writer',
        label: 'Worker writer',
        subtitle: 'put(key, value)',
        icon: 'compute',
        detail:
          'Writes go to central data stores. A write does not synchronously update every location’s cached value.',
        x: 140,
        y: 340,
        href: '#piece-writer',
      },
      {
        id: 'central',
        label: 'Central stores',
        subtitle: 'Persistent key/value data',
        icon: 'database',
        detail:
          'Central stores hold the data behind the cache hierarchy. Truly cold reads must reach these stores.',
        x: 450,
        y: 340,
        href: '#piece-central',
      },
      {
        id: 'other',
        label: 'Another location',
        subtitle: 'Its own cached view',
        icon: 'browser',
        detail:
          'Another location may still read an older value for 60 seconds or more. Avoid using KV reads as an atomic coordination mechanism.',
        x: 760,
        y: 340,
        href: '#piece-other',
      },
    ],
    edges: [
      {
        from: 'reader',
        to: 'edge',
        d: 'M165 87 L423 87',
        label: 'read',
        x: 295,
        y: 72,
      },
      {
        from: 'edge',
        to: 'regional',
        d: 'M475 87 L733 87',
        label: 'miss',
        x: 605,
        y: 72,
      },
      {
        from: 'regional',
        to: 'central',
        d: 'M735 87 L664 87 Q652 87 652 99 L652 232.5 Q652 244.5 640 244.5 L462 244.5 Q450 244.5 450 256.5 L450 343',
        label: 'miss',
        x: 605,
        y: 232.5,
      },
      {
        from: 'writer',
        to: 'central',
        d: 'M165 372 L425 372',
        label: 'write',
        x: 295,
        y: 357,
      },
      {
        from: 'other',
        to: 'central',
        d: 'M734 372 L475 372',
        label: 'cold read',
        x: 605,
        y: 357,
      },
    ],
  },
  r2: {
    title: 'How an object moves through R2',
    summary:
      'The documented R2 architecture: API entry points, metadata, read caching, and persistent object storage.',
    width: 900,
    height: 485,
    nodes: [
      {
        id: 'worker',
        label: 'Worker',
        subtitle: 'R2 binding',
        icon: 'compute',
        detail:
          'A Worker uses its bucket binding to read and write objects through the Workers API.',
        x: 140,
        y: 55,
        href: '#piece-worker',
      },
      {
        id: 'gateway',
        label: 'R2 Gateway',
        subtitle: 'Authentication + routing',
        icon: 'workflow',
        detail:
          'R2 routes API requests through its gateway, which handles authentication and coordinates access to metadata and object data.',
        x: 450,
        y: 55,
        href: '#piece-gateway',
      },
      {
        id: 'metadata',
        label: 'Metadata service',
        subtitle: 'Keys + checksums',
        icon: 'keys',
        detail:
          'The documented metadata layer uses Durable Objects to manage object metadata and support strong consistency.',
        x: 760,
        y: 55,
        href: '#piece-metadata',
      },
      {
        id: 's3',
        label: 'S3 client',
        subtitle: 'Compatible S3 operations',
        icon: 'code',
        detail:
          'An external S3 client uses R2’s S3-compatible endpoint. Check the compatibility table: support is not identical to all of AWS S3.',
        x: 140,
        y: 340,
        href: '#piece-s3',
      },
      {
        id: 'cache',
        label: 'Tiered read cache',
        subtitle: 'Faster object reads',
        icon: 'bucket',
        detail:
          'A read-cache layer sits in front of distributed storage and helps serve object data closer to clients.',
        x: 450,
        y: 340,
        href: '#piece-cache',
      },
      {
        id: 'storage',
        label: 'Distributed storage',
        subtitle: 'Persistent object bytes',
        icon: 'database',
        detail:
          'The storage infrastructure persistently stores encrypted object data. Metadata and object bytes are separate responsibilities.',
        x: 760,
        y: 340,
        href: '#piece-storage',
      },
    ],
    edges: [
      {
        from: 'worker',
        to: 'gateway',
        d: 'M165 87 L430 87',
        label: 'binding API',
        x: 295,
        y: 72,
      },
      {
        from: 's3',
        to: 'gateway',
        d: 'M167 381 L236 381 Q248 381 248 369 L248 242 Q248 230 260 230 L330 230 Q342 230 342 218 L342 99 Q342 87 354 87 L430 87',
        label: 'S3 API',
        x: 275,
        y: 218,
      },
      {
        from: 'gateway',
        to: 'metadata',
        d: 'M468 87 L733 87',
        label: 'metadata',
        x: 605,
        y: 72,
      },
      {
        from: 'gateway',
        to: 'cache',
        d: 'M468 87 L546 87 Q558 87 558 99 L558 293 Q558 305 546 305 L462 305 Q450 305 450 317 L450 344',
        label: 'read path',
        x: 606,
        y: 229.5,
      },
      {
        from: 'cache',
        to: 'storage',
        d: 'M470 372 L735 372',
        label: 'cache miss',
        x: 605,
        y: 357,
      },
    ],
  },
  d1: {
    title: 'From SQL to application data',
    summary:
      'Follow a Worker binding query through preparation, execution, and the result returned to your handler.',
    width: 900,
    height: 485,
    nodes: [
      {
        id: 'worker',
        label: 'Worker',
        subtitle: 'Application handler',
        icon: 'compute',
        detail:
          'Application code accesses a configured D1 database through its binding.',
        x: 140,
        y: 55,
        href: '#piece-worker',
      },
      {
        id: 'binding',
        label: 'D1 binding',
        subtitle: 'env.DB',
        icon: 'workflow',
        detail:
          'The binding exposes the D1 database API. Local development normally targets a separate local database, not production data.',
        x: 450,
        y: 55,
        href: '#piece-binding',
      },
      {
        id: 'statement',
        label: 'Prepared statement',
        subtitle: 'SQL + parameters',
        icon: 'code',
        detail:
          'Prepare a SQL statement, bind any parameters, and execute it through the D1 binding API.',
        x: 760,
        y: 55,
        href: '#piece-statement',
      },
      {
        id: 'application',
        label: 'Application data',
        subtitle: 'Use returned rows',
        icon: 'browser',
        detail:
          'Use the returned rows and result information in your application logic. The API offers different methods for selecting the result shape.',
        x: 140,
        y: 340,
        href: '#piece-application',
      },
      {
        id: 'result',
        label: 'Query result',
        subtitle: 'Rows + metadata',
        icon: 'message',
        detail:
          'Execution returns result data to your Worker. Usage accounting measures rows read and written, rather than simply counting SQL statements.',
        x: 450,
        y: 340,
        href: '#piece-result',
      },
      {
        id: 'database',
        label: 'D1 database',
        subtitle: 'SQLite SQL semantics',
        icon: 'database',
        detail:
          'D1 executes SQL against a managed database with SQLite semantics. Database size and query-duration limits still apply.',
        x: 760,
        y: 340,
        href: '#piece-database',
      },
    ],
    edges: [
      {
        from: 'worker',
        to: 'binding',
        d: 'M165 87 L430 87',
        label: 'binding',
        x: 295,
        y: 72,
      },
      {
        from: 'binding',
        to: 'statement',
        d: 'M468 87 L731 87',
        label: 'prepare / bind',
        x: 605,
        y: 72,
      },
      {
        from: 'statement',
        to: 'database',
        d: 'M787 96 L856 96 Q868 96 868 108 L868 293 Q868 305 856 305 L772 305 Q760 305 760 317 L760 343',
        label: 'execute',
        x: 814,
        y: 229.5,
      },
      {
        from: 'database',
        to: 'result',
        d: 'M737 372 L479 372',
        label: 'result',
        x: 605,
        y: 357,
      },
      {
        from: 'result',
        to: 'application',
        d: 'M423 372 L168 372',
        label: 'consume',
        x: 295,
        y: 357,
      },
    ],
  },
  'durable-objects': {
    title: 'One chat room, one named instance',
    summary:
      'An example: participants in the same room reach the same code and stored state. Each other room can have its own object.',
    width: 900,
    height: 485,
    regions: [
      {
        label: 'Persistent',
        detail: 'Stored data',
        x: 345,
        y: 275,
        width: 210,
        height: 200,
      },
      {
        label: 'Temporary',
        detail: 'Recreated',
        x: 655,
        y: 275,
        width: 210,
        height: 200,
      },
    ],
    nodes: [
      {
        id: 'caller',
        label: 'Caller Worker',
        subtitle: 'Object namespace binding',
        icon: 'compute',
        detail:
          'A Worker uses a Durable Object namespace binding to address a particular object.',
        x: 140,
        y: 55,
        href: '#piece-caller',
      },
      {
        id: 'identity',
        label: 'Room identity',
        subtitle: 'chat-room:123 → stub',
        icon: 'keys',
        detail:
          'Use the room name to address its Durable Object. Callers in the same room use the same identity; another room can use a different object.',
        x: 450,
        y: 55,
        href: '#piece-identity',
      },
      {
        id: 'object',
        label: 'Chat room object',
        subtitle: 'Your code + room state',
        icon: 'object',
        detail:
          'This object runs the room’s application logic and coordinates its participants. The same model can represent a game session, shared document, or tenant workspace.',
        x: 760,
        y: 55,
        href: '#piece-object',
      },
      {
        id: 'another',
        label: 'Another participant',
        subtitle: 'Same room name',
        icon: 'browser',
        detail:
          'A second caller can address the same named object rather than creating a separate copy of its state.',
        x: 140,
        y: 340,
        href: '#piece-another',
      },
      {
        id: 'private',
        label: 'Private SQLite',
        subtitle: 'Persisted room data',
        icon: 'database',
        detail:
          'The object’s private SQLite storage holds room data that must persist, such as message history. It stays attached to that object’s identity.',
        x: 450,
        y: 340,
        href: '#piece-private',
      },
      {
        id: 'memory',
        label: 'In-memory state',
        subtitle: 'Active room state',
        icon: 'compute',
        detail:
          'An active object can keep state in memory. Store information that must survive instance lifecycle changes in durable storage.',
        x: 760,
        y: 340,
        href: '#piece-memory',
      },
    ],
    edges: [
      {
        from: 'caller',
        to: 'identity',
        d: 'M165 87 L423 87',
        label: 'lookup',
        x: 295,
        y: 72,
      },
      {
        from: 'identity',
        to: 'object',
        d: 'M475 87 L731 87',
        label: 'RPC',
        x: 605,
        y: 72,
      },
      {
        from: 'another',
        to: 'identity',
        d: 'M166 381 L236 381 Q248 381 248 369 L248 242 Q248 230 260 230 L330 230 Q342 230 342 218 L342 99 Q342 87 354 87 L423 87',
        label: 'same identity',
        x: 275,
        y: 218,
      },
      {
        from: 'object',
        to: 'private',
        d: 'M733 96 L664 96 Q652 96 652 108 L652 236 Q652 248 640 248 L462 248 Q450 248 450 260 L450 343',
        label: 'durable state',
        x: 575,
        y: 236,
      },
      {
        from: 'object',
        to: 'memory',
        d: 'M787 96 L856 96 Q868 96 868 108 L868 293 Q868 305 856 305 L772 305 Q760 305 760 317 L760 345',
        label: 'active state',
        x: 814,
        y: 229.5,
      },
    ],
  },
  queues: {
    title: 'The life of a queued message',
    summary:
      'A push-consumer example, including the success and failure paths. Delivery can happen more than once.',
    width: 900,
    height: 485,
    nodes: [
      {
        id: 'producer',
        label: 'Producer Worker',
        subtitle: 'send / sendBatch',
        icon: 'compute',
        detail:
          'The producer publishes messages through a queue binding. A queue decouples request handling from background processing.',
        x: 140,
        y: 55,
        href: '#piece-producer',
      },
      {
        id: 'buffer',
        label: 'Queue buffer',
        subtitle: 'Messages wait here',
        icon: 'queue',
        detail:
          'The queue buffers messages until delivery. Retention limits apply, and delivery order is not guaranteed.',
        x: 450,
        y: 55,
        href: '#piece-buffer',
      },
      {
        id: 'consumer',
        label: 'Consumer Worker',
        subtitle: 'Process a batch',
        icon: 'compute',
        detail:
          'A push consumer runs when a batch is delivered. Make processing idempotent because a message can be delivered more than once.',
        x: 760,
        y: 55,
        href: '#piece-consumer',
      },
      {
        id: 'dead-letter',
        label: 'Dead-letter queue',
        subtitle: 'After retry limit',
        icon: 'queue',
        detail:
          'If configured, a dead-letter queue receives messages after the retry limit. Without one, those messages are deleted.',
        x: 140,
        y: 340,
        href: '#piece-dead-letter',
      },
      {
        id: 'retry',
        label: 'Retry',
        subtitle: 'Failed processing',
        icon: 'clock',
        detail:
          'A failed batch or an explicit retry can cause another delivery. Individual acknowledgements prevent successfully processed messages from being retried with the rest.',
        x: 450,
        y: 340,
        href: '#piece-retry',
      },
      {
        id: 'ack',
        label: 'Acknowledge',
        subtitle: 'Successful processing',
        icon: 'message',
        detail:
          'Successful processing or explicit acknowledgement lets Queues remove the message. This is separate from publishing it.',
        x: 760,
        y: 340,
        href: '#piece-ack',
      },
    ],
    edges: [
      {
        from: 'producer',
        to: 'buffer',
        d: 'M165 87 L423 87',
        label: 'publish',
        x: 295,
        y: 72,
        kind: 'message',
      },
      {
        from: 'buffer',
        to: 'consumer',
        d: 'M475 87 L733 87',
        label: 'deliver batch',
        x: 605,
        y: 72,
        kind: 'message',
      },
      {
        from: 'consumer',
        to: 'ack',
        d: 'M785 96 L856 96 Q868 96 868 108 L868 293 Q868 305 856 305 L772 305 Q760 305 760 317 L760 351',
        label: 'success',
        x: 814,
        y: 229.5,
      },
      {
        from: 'consumer',
        to: 'retry',
        d: 'M735 96 L664 96 Q652 96 652 108 L652 228 Q652 240 640 240 L462 240 Q450 240 450 252 L450 342',
        label: 'failure',
        x: 665,
        y: 228,
        kind: 'return',
      },
      {
        from: 'retry',
        to: 'buffer',
        d: 'M427 372 L354 372 Q342 372 342 360 L342 99 Q342 87 354 87 L423 87',
        label: 'redeliver',
        x: 294,
        y: 229.5,
        kind: 'return',
      },
      {
        from: 'retry',
        to: 'dead-letter',
        d: 'M427 372 L167 372',
        label: 'exhausted',
        x: 295,
        y: 357,
        kind: 'return',
      },
    ],
  },
  workflows: {
    title: 'Execution that resumes between steps',
    summary:
      'An example instance with durable steps, retries, and a pause for time or an external event.',
    width: 900,
    height: 705,
    nodes: [
      {
        id: 'trigger',
        label: 'Trigger',
        subtitle: 'Worker / CLI / API',
        icon: 'compute',
        detail:
          'Create an instance and pass initial parameters. Each instance has its own execution and state.',
        x: 140,
        y: 55,
        href: '#piece-trigger',
      },
      {
        id: 'step',
        label: 'Durable step',
        subtitle: 'step.do',
        icon: 'code',
        detail:
          'Run work inside a step. Return data from the step to persist it for subsequent execution.',
        x: 450,
        y: 55,
        href: '#piece-step',
      },
      {
        id: 'pause',
        label: 'Sleep or wait',
        subtitle: 'Time / external event',
        icon: 'clock',
        detail:
          'A Workflow can sleep until a time or wait for an external event before continuing. These are optional control-flow choices.',
        x: 760,
        y: 55,
        href: '#piece-pause',
      },
      {
        id: 'retry',
        label: 'Retry policy',
        subtitle: 'Reattempt failed step',
        icon: 'workflow',
        detail:
          'Step retry configuration controls attempts, delays, and backoff. A failed step can be retried without restarting the entire sequence of completed steps.',
        x: 140,
        y: 340,
        href: '#piece-retry',
      },
      {
        id: 'state',
        label: 'Persisted state',
        subtitle: 'Step results',
        icon: 'database',
        detail:
          'Step results are persisted. Initial event payloads are not a replacement for mutable durable state.',
        x: 450,
        y: 340,
        href: '#piece-state',
      },
      {
        id: 'next',
        label: 'Next step',
        subtitle: 'Resume the instance',
        icon: 'code',
        detail:
          'The instance continues through further steps after work or waiting completes. The diagram shows an example, not a required sequence for every Workflow.',
        x: 760,
        y: 340,
        href: '#piece-next',
      },
      {
        id: 'service',
        label: 'Worker service',
        subtitle: 'Optional RPC / HTTP call',
        icon: 'compute',
        x: 760,
        y: 560,
        href: '#piece-service',
        detail:
          'A Workflow step can call another Worker through a configured service binding. This is optional: the Workflow already runs its own step code.',
      },
    ],
    edges: [
      {
        from: 'trigger',
        to: 'step',
        d: 'M165 87 L421 87',
        label: 'create',
        x: 295,
        y: 72,
      },
      {
        from: 'step',
        to: 'pause',
        d: 'M477 87 L735 87',
        label: 'continue',
        x: 605,
        y: 72,
      },
      {
        from: 'step',
        to: 'retry',
        d: 'M423 96 L354 96 Q342 96 342 108 L342 206 Q342 218 330 218 L152 218 Q140 218 140 230 L140 371',
        label: 'on failure',
        x: 265,
        y: 206,
        kind: 'return',
      },
      {
        from: 'retry',
        to: 'step',
        d: 'M112 355 H47 Q35 355 35 343 V32 Q35 20 47 20 H438 Q450 20 450 32 V60',
        label: 'retry',
        x: 65,
        y: 255,
        kind: 'return',
      },
      {
        from: 'step',
        to: 'state',
        d: 'M477 96 L546 96 Q558 96 558 108 L558 293 Q558 305 546 305 L462 305 Q450 305 450 317 L450 343',
        label: 'persist result',
        x: 606,
        y: 229.5,
      },
      {
        from: 'pause',
        to: 'next',
        d: 'M783 87 L856 87 Q868 87 868 99 L868 293 Q868 305 856 305 L772 305 Q760 305 760 317 L760 345',
        label: 'resume',
        x: 814,
        y: 229.5,
      },
      {
        from: 'state',
        to: 'next',
        d: 'M473 372 L731 372',
        label: 'prior results',
        x: 605,
        y: 357,
      },
      {
        from: 'next',
        to: 'service',
        d: 'M787 381 L856 381 Q868 381 868 393 L868 513 Q868 525 856 525 L772 525 Q760 525 760 537 L760 565',
        label: 'call service',
        x: 814,
        y: 482,
      },
    ],
  },
} satisfies Record<string, Diagram>;
